/**
 * src/router.tsx
 * Oracle Document sections consumed: 2, 7, 8, 9, 10, 12
 * Last item from Section 11 risks addressed here: Mixed response envelopes
 */
import { Suspense, type ReactNode } from 'react';
import { createBrowserRouter, Navigate, Outlet } from 'react-router-dom';
import { AuthGuard, PublicOnlyGuard, RoleGuard } from '@/utils/guards';
import { AppShell } from '@/components/layout/AppShell';
import { routes } from '@/routes/routes';
import {
  AiAssistantPage,
  AnalyticsPage,
  ApiValidationPage,
  ChainPage,
  CreditPage,
  CustomerDetailPage,
  CustomersPage,
  DashboardPage,
  DecisionsPage,
  DeveloperPage,
  EInvoicingPage,
  EventsPage,
  FinancePage,
  FinancialCalendarPage,
  ForbiddenPage,
  ForecastingPage,
  ForgotPasswordPage,
  GstPage,
  I18nPage,
  InventoryDetailPage,
  InventoryFormPage,
  InventoryPage,
  InventoryReceiptsPage,
  InventoryVisionPage,
  BarcodesPage,
  KycPage,
  LoginPage,
  LoyaltyPage,
  MarketplacePage,
  MarketIntelligencePage,
  MfaSetupPage,
  MfaVerifyPage,
  NotFoundPage,
  OfflinePage,
  OpsPage,
  PosPage,
  ReportsPage,
  PricingPage,
  ReturnsPage,
  PurchaseOrderCreatePage,
  PurchaseOrderDetailPage,
  PurchaseOrderEditPage,
  PurchaseOrdersPage,
  ReceiptsQueuePage,
  ReceiptsTemplatePage,
  RegisterPage,
  ResetPasswordPage,
  ServerErrorPage,
  SmartAlertsPage,
  StaffPerformanceDetailPage,
  StaffPerformancePage,
  StockAuditPage,
  StoreCategoriesPage,
  StoreProfilePage,
  StoreTaxConfigPage,
  OperationsPage,
  SupplierDetailPage,
  SupplierCreatePage,
  SupplierEditPage,
  SupplierPage,
  TeamPage,
  TransactionDetailPage,
  TransactionsPage,
  VerifyOtpPage,
  VisionOcrReviewPage,
  VisionOcrUploadPage,
  WhatsAppPage,
} from './router-pages';

const suspense = (element: ReactNode) => (
  <Suspense fallback={<div className="app-content">Loading…</div>}>{element}</Suspense>
);

export const appRoutes = [
  { path: routes.developerLegacy, element: <Navigate to={routes.developer} replace /> },
  { path: routes.kycLegacy, element: <Navigate to={routes.kyc} replace /> },
  { path: routes.teamLegacy, element: <Navigate to={routes.team} replace /> },
  { path: routes.opsLegacy, element: <Navigate to={routes.ops} replace /> },
  {
    element: <Outlet />,
    children: [
      {
        element: <PublicOnlyGuard />,
        children: [
          { path: '/login', element: suspense(<LoginPage />) },
          { path: routes.authLogin, element: suspense(<LoginPage />) },
          { path: routes.register, element: suspense(<RegisterPage />) },
          { path: routes.authRegister, element: suspense(<RegisterPage />) },
          { path: routes.verifyOtp, element: suspense(<VerifyOtpPage />) },
          { path: routes.authOtp, element: suspense(<VerifyOtpPage />) },
          { path: routes.mfa, element: suspense(<MfaSetupPage />) },
          { path: routes.mfaSetup, element: suspense(<MfaSetupPage />) },
          { path: routes.mfaVerify, element: suspense(<MfaVerifyPage />) },
          { path: routes.forgotPassword, element: suspense(<ForgotPasswordPage />) },
          { path: routes.resetPassword, element: suspense(<ResetPasswordPage />) },
        ],
      },
      {
        element: <AuthGuard />,
        children: [
          {
            element: <AppShell />,
            children: [
              { path: '/', element: <Navigate to={routes.dashboard} replace /> },
              { path: routes.dashboard, element: suspense(<DashboardPage />) },
              { path: routes.smartAlerts, element: suspense(<SmartAlertsPage />) },
              { path: routes.reports, element: suspense(<ReportsPage />) },
              { path: routes.financialCalendar, element: suspense(<FinancialCalendarPage />) },
              { path: routes.pos, element: suspense(<PosPage />) },
              { path: routes.transactions, element: suspense(<TransactionsPage />) },
              { path: routes.returns, element: suspense(<ReturnsPage />) },
              { path: routes.transactionDetail, element: suspense(<TransactionDetailPage />) },
              { path: routes.inventory, element: suspense(<InventoryPage />) },
              { path: routes.inventoryNew, element: suspense(<InventoryFormPage />) },
              { path: routes.inventoryDetail, element: suspense(<InventoryDetailPage />) },
              { path: routes.inventoryEdit, element: suspense(<InventoryFormPage />) },
              { path: routes.stockAudit, element: suspense(<StockAuditPage />) },
              { path: routes.storeProfile, element: suspense(<StoreProfilePage />) },
              { path: routes.storeCategories, element: suspense(<StoreCategoriesPage />) },
              { path: routes.storeTaxConfig, element: suspense(<StoreTaxConfigPage />) },
              { path: routes.suppliers, element: suspense(<SupplierPage />) },
              { path: routes.supplierNew, element: suspense(<SupplierCreatePage />) },
              { path: routes.supplierDetail, element: suspense(<SupplierDetailPage />) },
              { path: routes.supplierEdit, element: suspense(<SupplierEditPage />) },
              { path: routes.purchaseOrders, element: suspense(<PurchaseOrdersPage />) },
              { path: routes.purchaseOrderCreate, element: suspense(<PurchaseOrderCreatePage />) },
              { path: routes.purchaseOrderDetail, element: suspense(<PurchaseOrderDetailPage />) },
              { path: routes.purchaseOrderEdit, element: suspense(<PurchaseOrderEditPage />) },
              { path: routes.inventoryReceipts, element: suspense(<InventoryReceiptsPage />) },
              { path: routes.receiptsTemplate, element: suspense(<ReceiptsTemplatePage />) },
              { path: routes.receiptsQueue, element: suspense(<ReceiptsQueuePage />) },
              { path: routes.inventoryBarcodes, element: suspense(<BarcodesPage />) },
              { path: routes.inventoryVision, element: suspense(<InventoryVisionPage />) },
              { path: routes.inventoryVisionReview, element: suspense(<InventoryVisionPage />) },
              { path: routes.visionOcr, element: suspense(<VisionOcrUploadPage />) },
              { path: routes.visionOcrReview, element: suspense(<VisionOcrReviewPage />) },
              { path: routes.kyc, element: suspense(<KycPage />) },
              { path: routes.developer, element: suspense(<DeveloperPage />) },
              { path: routes.team, element: suspense(<TeamPage />) },
              { path: routes.operations, element: suspense(<OperationsPage />) },
              { path: routes.ops, element: suspense(<OpsPage />) },
              { path: routes.apiValidation, element: suspense(<ApiValidationPage />) },
              { path: routes.customers, element: suspense(<CustomersPage />) },
              { path: routes.customerDetail, element: suspense(<CustomerDetailPage />) },
              { path: routes.staff, element: suspense(<StaffPerformancePage />) },
              { path: routes.staffDetail, element: suspense(<RoleGuard role="owner"><StaffPerformanceDetailPage /></RoleGuard>) },
              { path: routes.pricing, element: suspense(<RoleGuard role="owner"><PricingPage /></RoleGuard>) },
              { path: routes.decisions, element: suspense(<RoleGuard role="owner"><DecisionsPage /></RoleGuard>) },
              { path: routes.einvoice, element: suspense(<EInvoicingPage />) },
              { path: routes.ai, element: suspense(<AiAssistantPage />) },
              { path: routes.offline, element: suspense(<OfflinePage />) },
              { path: routes.marketplace, element: suspense(<MarketplacePage />) },
              { path: routes.marketplaceLegacy, element: <Navigate to={routes.marketplace} replace /> },
              { path: routes.chain, element: suspense(<ChainPage />) },
              { path: routes.chainLegacy, element: <Navigate to={routes.chain} replace /> },
              { path: routes.whatsapp, element: suspense(<WhatsAppPage />) },
              { path: routes.i18n, element: suspense(<I18nPage />) },
              { path: routes.analytics, element: suspense(<RoleGuard role="owner"><AnalyticsPage /></RoleGuard>) },
              { path: routes.marketIntelligence, element: suspense(<RoleGuard role="owner"><MarketIntelligencePage /></RoleGuard>) },
              { path: routes.events, element: suspense(<EventsPage />) },
              { path: routes.financeGst, element: suspense(<GstPage />) },
              { path: routes.gst, element: <Navigate to={routes.financeGst} replace /> },
              { path: routes.loyalty, element: suspense(<LoyaltyPage />) },
              { path: routes.credit, element: suspense(<CreditPage />) },
              { path: routes.forecasting, element: suspense(<RoleGuard role="owner"><ForecastingPage /></RoleGuard>) },
              { path: routes.finance, element: suspense(<FinancePage />) },
              { path: routes.financeEinvoice, element: suspense(<EInvoicingPage />) },
              { path: routes.einvoice, element: <Navigate to={routes.financeEinvoice} replace /> },
              { path: routes.forbidden, element: suspense(<ForbiddenPage />) },
              { path: routes.serverError, element: suspense(<ServerErrorPage />) },
              { path: routes.notFound, element: suspense(<NotFoundPage />) },
            ],
          },
        ],
      },
    ],
  },
];

export const router = createBrowserRouter(appRoutes);
