/**
 * src/router.tsx
 * Oracle Document sections consumed: 2, 7, 8, 9, 10, 12
 * Last item from Section 11 risks addressed here: Mixed response envelopes
 */
import { Suspense, type ReactNode } from 'react';
import { createBrowserRouter, Navigate, Outlet } from 'react-router-dom';
import { AuthGuard, PublicOnlyGuard, RoleGuard } from '@/utils/guards';
import { AppShell } from '@/components/layout/AppShell';
import {
  AiAssistantPage,
  AnalyticsPage,
  ApiValidationPage,
  ChainPage,
  CreditPage,
  CustomerDetailPage,
  CustomersPage,
  DashboardPage,
  DecisionsPage,
  DeveloperPage,
  EInvoicingPage,
  EventsPage,
  FinancePage,
  ForbiddenPage,
  ForecastingPage,
  ForgotPasswordPage,
  GstPage,
  I18nPage,
  InventoryDetailPage,
  InventoryFormPage,
  InventoryPage,
  KycPage,
  LoginPage,
  LoyaltyPage,
  MarketplacePage,
  MarketIntelligencePage,
  MfaSetupPage,
  MfaVerifyPage,
  NotFoundPage,
  OfflinePage,
  PosPage,
  PricingPage,
  PurchaseOrderCreatePage,
  PurchaseOrderDetailPage,
  PurchaseOrderEditPage,
  PurchaseOrdersPage,
  ReceiptsQueuePage,
  ReceiptsTemplatePage,
  RegisterPage,
  ResetPasswordPage,
  ServerErrorPage,
  StaffPerformanceDetailPage,
  StaffPerformancePage,
  StockAuditPage,
  StoreCategoriesPage,
  StoreProfilePage,
  StoreTaxConfigPage,
  SupplierDetailPage,
  SupplierCreatePage,
  SupplierEditPage,
  SupplierPage,
  TransactionDetailPage,
  TransactionsPage,
  VerifyOtpPage,
  VisionOcrReviewPage,
  VisionOcrUploadPage,
  WhatsAppPage,
} from './router-pages';

const suspense = (element: ReactNode) => (
  <Suspense fallback={<div className="app-content">Loading…</div>}>{element}</Suspense>
);

export const router = createBrowserRouter([
  {
    element: <Outlet />,
    children: [
      {
        element: <PublicOnlyGuard />,
        children: [
          { path: '/login', element: suspense(<LoginPage />) },
          { path: '/auth/login', element: suspense(<LoginPage />) },
          { path: '/register', element: suspense(<RegisterPage />) },
          { path: '/auth/register', element: suspense(<RegisterPage />) },
          { path: '/verify-otp', element: suspense(<VerifyOtpPage />) },
          { path: '/auth/otp', element: suspense(<VerifyOtpPage />) },
          { path: '/mfa-setup', element: suspense(<MfaSetupPage />) },
          { path: '/mfa-verify', element: suspense(<MfaVerifyPage />) },
          { path: '/forgot-password', element: suspense(<ForgotPasswordPage />) },
          { path: '/reset-password', element: suspense(<ResetPasswordPage />) },
        ],
      },
      {
        element: <AuthGuard />,
        children: [
          {
            element: <AppShell />,
            children: [
              { path: '/', element: <Navigate to="/dashboard" replace /> },
              { path: '/dashboard', element: suspense(<DashboardPage />) },
              { path: '/pos', element: suspense(<PosPage />) },
              { path: '/transactions', element: suspense(<TransactionsPage />) },
              { path: '/transactions/:id', element: suspense(<TransactionDetailPage />) },
              { path: '/inventory', element: suspense(<InventoryPage />) },
              { path: '/inventory/new', element: suspense(<InventoryFormPage />) },
              { path: '/inventory/:productId', element: suspense(<InventoryDetailPage />) },
              { path: '/inventory/:productId/edit', element: suspense(<InventoryFormPage />) },
              { path: '/inventory/stock-audit', element: suspense(<StockAuditPage />) },
              { path: '/store/profile', element: suspense(<StoreProfilePage />) },
              { path: '/store/categories', element: suspense(<StoreCategoriesPage />) },
              { path: '/store/tax-config', element: suspense(<StoreTaxConfigPage />) },
              { path: '/suppliers', element: suspense(<SupplierPage />) },
              { path: '/suppliers/new', element: suspense(<SupplierCreatePage />) },
              { path: '/suppliers/:id', element: suspense(<SupplierDetailPage />) },
              { path: '/suppliers/:id/edit', element: suspense(<SupplierEditPage />) },
              { path: '/purchase-orders', element: suspense(<PurchaseOrdersPage />) },
              { path: '/purchase-orders/create', element: suspense(<PurchaseOrderCreatePage />) },
              { path: '/purchase-orders/:id', element: suspense(<PurchaseOrderDetailPage />) },
              { path: '/purchase-orders/:id/edit', element: suspense(<PurchaseOrderEditPage />) },
              { path: '/receipts/template', element: suspense(<ReceiptsTemplatePage />) },
              { path: '/receipts/queue', element: suspense(<ReceiptsQueuePage />) },
              { path: '/vision/ocr', element: suspense(<VisionOcrUploadPage />) },
              { path: '/vision/ocr/:jobId', element: suspense(<VisionOcrReviewPage />) },
              { path: '/kyc', element: suspense(<KycPage />) },
              { path: '/developer', element: suspense(<DeveloperPage />) },
              { path: '/api-validation', element: suspense(<ApiValidationPage />) },
              { path: '/customers', element: suspense(<CustomersPage />) },
              { path: '/customers/:customerId', element: suspense(<CustomerDetailPage />) },
              { path: '/staff-performance', element: suspense(<StaffPerformancePage />) },
              { path: '/staff-performance/:userId', element: suspense(<RoleGuard role="owner"><StaffPerformanceDetailPage /></RoleGuard>) },
              { path: '/pricing', element: suspense(<RoleGuard role="owner"><PricingPage /></RoleGuard>) },
              { path: '/decisions', element: suspense(<RoleGuard role="owner"><DecisionsPage /></RoleGuard>) },
              { path: '/e-invoicing', element: suspense(<EInvoicingPage />) },
              { path: '/ai-assistant', element: suspense(<AiAssistantPage />) },
              { path: '/offline', element: suspense(<OfflinePage />) },
              { path: '/marketplace', element: suspense(<MarketplacePage />) },
              { path: '/chain', element: suspense(<ChainPage />) },
              { path: '/whatsapp', element: suspense(<WhatsAppPage />) },
              { path: '/i18n', element: suspense(<I18nPage />) },
              { path: '/analytics', element: suspense(<RoleGuard role="owner"><AnalyticsPage /></RoleGuard>) },
              { path: '/market-intelligence', element: suspense(<RoleGuard role="owner"><MarketIntelligencePage /></RoleGuard>) },
              { path: '/events', element: suspense(<EventsPage />) },
              { path: '/gst', element: suspense(<RoleGuard role="owner"><GstPage /></RoleGuard>) },
              { path: '/loyalty', element: suspense(<LoyaltyPage />) },
              { path: '/credit', element: suspense(<CreditPage />) },
              { path: '/forecasting', element: suspense(<RoleGuard role="owner"><ForecastingPage /></RoleGuard>) },
              { path: '/finance', element: suspense(<FinancePage />) },
              { path: '/403', element: suspense(<ForbiddenPage />) },
              { path: '/500', element: suspense(<ServerErrorPage />) },
              { path: '*', element: suspense(<NotFoundPage />) },
            ],
          },
        ],
      },
    ],
  },
]);
