import { Suspense, type ReactNode } from 'react';
import { createBrowserRouter, Navigate, Outlet, useParams } from 'react-router-dom';
import { AuthGuard, PublicOnlyGuard, RoleGuard } from '@/utils/guards';
import { AppShell } from '@/components/layout/AppShell';
import { routes } from '@/routes/routes';
import {
  AiAssistantPage,
  AiToolsPage,
  AlertsPage,
  AnalyticsForecastingPage,
  AnalyticsMarketPage,
  AnalyticsOfflinePage,
  AnalyticsPage,
  AnalyticsStaffPage,
  ApiValidationPage,
  BarcodesPage,
  CalendarPage,
  ChainPage,
  CreditPage,
  CustomerAnalyticsPage,
  CustomerDetailPage,
  CustomersPage,
  DashboardPage,
  DecisionsPage,
  DeveloperPage,
  EInvoicingPage,
  FinanceAccountsPage,
  FinanceCreditScorePage,
  FinanceKycPage,
  FinanceLedgerPage,
  FinanceLoansPage,
  FinancePage,
  FinanceTreasuryPage,
  FinancialCalendarPage,
  ForbiddenPage,
  ForecastingPage,
  ForgotPasswordPage,
  GstPage,
  I18nPage,
  InventoryDetailPage,
  InventoryFormPage,
  InventoryPage,
  InventoryPricingPage,
  InventoryReceiptsPage,
  InventorySyncPage,
  InventoryVisionPage,
  KycPage,
  LoginPage,
  LoyaltyPage,
  MarketplacePage,
  MarketIntelligencePage,
  MfaSetupPage,
  MfaVerifyPage,
  NotFoundPage,
  OfflinePage,
  OmnichannelPage,
  OperationsPage,
  OpsPage,
  OrdersPage,
  PosPage,
  PricingPage,
  PurchaseOrderCreatePage,
  PurchaseOrderDetailPage,
  PurchaseOrderEditPage,
  PurchaseOrdersPage,
  ReceiptsQueuePage,
  ReceiptsTemplatePage,
  RegisterPage,
  ReportsPage,
  ResetPasswordPage,
  ReturnsPage,
  SecurityPage,
  ServerErrorPage,
  SmartAlertsPage,
  StaffPerformanceDetailPage,
  StaffPerformancePage,
  StockAuditPage,
  StoreCategoriesPage,
  StoreProfilePage,
  StoreTaxConfigPage,
  SupplierCreatePage,
  SupplierDetailPage,
  SupplierEditPage,
  SupplierPage,
  TeamPage,
  TransactionDetailPage,
  TransactionsPage,
  VerifyOtpPage,
  VisionOcrReviewPage,
  VisionOcrUploadPage,
  WhatsAppPage,
} from './router-pages';

const suspense = (element: ReactNode) => (
  <Suspense fallback={<div className="app-content">Loading…</div>}>{element}</Suspense>
);

function LegacyTransactionDetailRedirect() {
  const { id } = useParams();
  return <Navigate to={id ? routes.orderTransactionDetail.replace(':uuid', id) : routes.ordersTransactions} replace />;
}

export const appRoutes = [
  { path: routes.developerLegacy, element: <Navigate to={routes.developer} replace /> },
  { path: routes.kycLegacy, element: <Navigate to={routes.kyc} replace /> },
  { path: routes.teamLegacy, element: <Navigate to={routes.team} replace /> },
  { path: routes.opsLegacy, element: <Navigate to={routes.ops} replace /> },
  { path: routes.marketplaceLegacy, element: <Navigate to={routes.marketplace} replace /> },
  { path: routes.chainLegacy, element: <Navigate to={routes.chain} replace /> },
  { path: routes.legacyAiAssistant, element: <Navigate to={routes.ai} replace /> },
  { path: routes.legacyAiTools, element: <Navigate to={routes.aiTools} replace /> },
  { path: routes.legacyDecisions, element: <Navigate to={routes.decisions} replace /> },
  { path: routes.i18n, element: <Navigate to={routes.settingsI18n} replace /> },
  { path: routes.events, element: <Navigate to={routes.financialCalendar} replace /> },
  { path: routes.analyticsStaff, element: <Navigate to={routes.staff} replace /> },
  { path: routes.analyticsForecasting, element: <Navigate to={routes.forecasting} replace /> },
  { path: routes.analyticsOffline, element: <Navigate to={routes.offline} replace /> },
  { path: routes.analyticsMarket, element: <Navigate to={routes.marketIntelligence} replace /> },
  { path: routes.inventoryPricing, element: <Navigate to={routes.pricing} replace /> },
  { path: routes.aiDecisions, element: <Navigate to={routes.decisions} replace /> },
  { path: routes.gst, element: <Navigate to={routes.financeGst} replace /> },
  { path: routes.einvoice, element: <Navigate to={routes.financeEinvoice} replace /> },
  { path: routes.storeProfile, element: <Navigate to={routes.settingsProfile} replace /> },
  { path: routes.storeCategories, element: <Navigate to={routes.settingsCategories} replace /> },
  { path: routes.storeTaxConfig, element: <Navigate to={routes.settingsTax} replace /> },
  { path: routes.legacyStoreProfile, element: <Navigate to={routes.settingsProfile} replace /> },
  { path: routes.legacyStoreCategories, element: <Navigate to={routes.settingsCategories} replace /> },
  { path: routes.legacyStoreTaxConfig, element: <Navigate to={routes.settingsTax} replace /> },
  { path: routes.legacySecurity, element: <Navigate to={routes.settingsSecurity} replace /> },
  { path: routes.pos, element: <Navigate to={routes.ordersPos} replace /> },
  { path: routes.transactions, element: <Navigate to={routes.ordersTransactions} replace /> },
  { path: routes.transactionDetail, element: <LegacyTransactionDetailRedirect /> },
  {
    element: <Outlet />,
    children: [
      {
        element: <PublicOnlyGuard />,
        children: [
          { path: '/login', element: suspense(<LoginPage />) },
          { path: routes.authLogin, element: suspense(<LoginPage />) },
          { path: routes.register, element: suspense(<RegisterPage />) },
          { path: routes.authRegister, element: suspense(<RegisterPage />) },
          { path: routes.verifyOtp, element: suspense(<VerifyOtpPage />) },
          { path: routes.authOtp, element: suspense(<VerifyOtpPage />) },
          { path: routes.mfa, element: suspense(<MfaSetupPage />) },
          { path: routes.mfaSetup, element: suspense(<MfaSetupPage />) },
          { path: routes.mfaVerify, element: suspense(<MfaVerifyPage />) },
          { path: routes.forgotPassword, element: suspense(<ForgotPasswordPage />) },
          { path: routes.resetPassword, element: suspense(<ResetPasswordPage />) },
        ],
      },
      {
        element: <AuthGuard />,
        children: [
          {
            element: <AppShell />,
            children: [
              { path: '/', element: <Navigate to={routes.dashboard} replace /> },
              { path: routes.dashboard, element: suspense(<DashboardPage />) },
              { path: routes.smartAlerts, element: suspense(<SmartAlertsPage />) },
              { path: routes.reports, element: suspense(<ReportsPage />) },
              { path: routes.financialCalendar, element: suspense(<FinancialCalendarPage />) },
              { path: routes.orders, element: suspense(<OrdersPage />) },
              { path: routes.ordersPos, element: suspense(<PosPage />) },
              { path: routes.ordersTransactions, element: suspense(<TransactionsPage />) },
              { path: routes.orderTransactionDetail, element: suspense(<TransactionDetailPage />) },
              { path: routes.returns, element: suspense(<ReturnsPage />) },
              { path: routes.inventory, element: suspense(<InventoryPage />) },
              { path: routes.inventoryNew, element: suspense(<InventoryFormPage />) },
              { path: routes.inventoryDetail, element: suspense(<InventoryDetailPage />) },
              { path: routes.inventoryEdit, element: suspense(<InventoryFormPage />) },
              { path: routes.stockAudit, element: suspense(<StockAuditPage />) },
              { path: routes.inventorySync, element: suspense(<InventorySyncPage />) },
              { path: routes.inventoryReceipts, element: suspense(<InventoryReceiptsPage />) },
              { path: routes.receiptsTemplate, element: suspense(<ReceiptsTemplatePage />) },
              { path: routes.receiptsQueue, element: suspense(<ReceiptsQueuePage />) },
              { path: routes.inventoryBarcodes, element: suspense(<BarcodesPage />) },
              { path: routes.inventoryVision, element: suspense(<InventoryVisionPage />) },
              { path: routes.inventoryVisionReview, element: suspense(<InventoryVisionPage />) },
              { path: routes.visionOcr, element: suspense(<VisionOcrUploadPage />) },
              { path: routes.visionOcrReview, element: suspense(<VisionOcrReviewPage />) },
              { path: routes.customers, element: suspense(<CustomersPage />) },
              { path: routes.customerDetail, element: suspense(<CustomerDetailPage />) },
              { path: routes.customersAnalytics, element: suspense(<CustomerAnalyticsPage />) },
              { path: routes.loyalty, element: suspense(<LoyaltyPage />) },
              { path: routes.credit, element: suspense(<CreditPage />) },
              { path: routes.whatsapp, element: suspense(<WhatsAppPage />) },
              { path: routes.analytics, element: suspense(<RoleGuard role="owner"><AnalyticsPage /></RoleGuard>) },
              { path: routes.analyticsMarket, element: suspense(<RoleGuard role="owner"><MarketIntelligencePage /></RoleGuard>) },
              { path: routes.marketIntelligence, element: suspense(<RoleGuard role="owner"><MarketIntelligencePage /></RoleGuard>) },
              { path: routes.analyticsStaff, element: suspense(<StaffPerformancePage />) },
              { path: routes.analyticsOffline, element: suspense(<OfflinePage />) },
              { path: routes.forecasting, element: suspense(<RoleGuard role="owner"><ForecastingPage /></RoleGuard>) },
              { path: routes.pricing, element: suspense(<RoleGuard role="owner"><PricingPage /></RoleGuard>) },
              { path: routes.decisions, element: suspense(<RoleGuard role="owner"><DecisionsPage /></RoleGuard>) },
              { path: routes.finance, element: suspense(<FinancePage />) },
              { path: routes.financeAccounts, element: suspense(<RoleGuard role="owner"><FinanceAccountsPage /></RoleGuard>) },
              { path: routes.financeCreditScore, element: suspense(<RoleGuard role="owner"><FinanceCreditScorePage /></RoleGuard>) },
              { path: routes.financeKyc, element: suspense(<RoleGuard role="owner"><FinanceKycPage /></RoleGuard>) },
              { path: routes.financeLedger, element: suspense(<RoleGuard role="owner"><FinanceLedgerPage /></RoleGuard>) },
              { path: routes.financeTreasury, element: suspense(<RoleGuard role="owner"><FinanceTreasuryPage /></RoleGuard>) },
              { path: routes.financeLoans, element: suspense(<RoleGuard role="owner"><FinanceLoansPage /></RoleGuard>) },
              { path: routes.financeGst, element: suspense(<GstPage />) },
              { path: routes.financeEinvoice, element: suspense(<EInvoicingPage />) },
              { path: routes.ai, element: suspense(<AiAssistantPage />) },
              { path: routes.aiTools, element: suspense(<AiToolsPage />) },
              { path: routes.marketplace, element: suspense(<MarketplacePage />) },
              { path: routes.omnichannel, element: suspense(<OmnichannelPage />) },
              { path: routes.chain, element: suspense(<ChainPage />) },
              { path: routes.settingsI18n, element: suspense(<I18nPage />) },
              { path: routes.settingsProfile, element: suspense(<StoreProfilePage />) },
              { path: routes.settingsCategories, element: suspense(<StoreCategoriesPage />) },
              { path: routes.settingsTax, element: suspense(<StoreTaxConfigPage />) },
              { path: routes.settingsSecurity, element: suspense(<SecurityPage />) },
              { path: routes.operations, element: suspense(<OperationsPage />) },
              { path: routes.ops, element: suspense(<OpsPage />) },
              { path: routes.developer, element: suspense(<DeveloperPage />) },
              { path: routes.kyc, element: suspense(<KycPage />) },
              { path: routes.team, element: suspense(<TeamPage />) },
              { path: routes.apiValidation, element: suspense(<ApiValidationPage />) },
              { path: routes.staff, element: suspense(<StaffPerformancePage />) },
              { path: routes.staffDetail, element: suspense(<RoleGuard role="owner"><StaffPerformanceDetailPage /></RoleGuard>) },
              { path: routes.forbidden, element: suspense(<ForbiddenPage />) },
              { path: routes.serverError, element: suspense(<ServerErrorPage />) },
              { path: routes.notFound, element: suspense(<NotFoundPage />) },
            ],
          },
        ],
      },
    ],
  },
];

export const router = createBrowserRouter(appRoutes);
